# Generated by Django 4.0.3 on 2023-04-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='message',
        ),
    ]
