# Generated by Django 4.2 on 2023-04-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0002_rename_name_image_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='choices',
            field=models.CharField(choices=[('0', 'LSB'), ('1', 'DWT'), ('2', 'EMD'), ('3', 'PVD')], default='0', max_length=20),
        ),
    ]
