# Generated by Django 4.2 on 2023-04-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0003_image_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='choices',
            field=models.CharField(choices=[('lsb', 'LSB'), ('dwt', 'DWT'), ('emd', 'EMD'), ('pvd', 'PVD')], default='0', max_length=20),
        ),
    ]
